version: '3.8'

services:
  localstack:
    image: "localstack/localstack:stable"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ssm
    volumes:
      - "./local-stack-init.sh:/etc/localstack/init/ready.d/init-aws.sh"